perl:
  - "5.16"
#  - "5.8"
env:
  - TARGET=normal
  - TARGET=perl
  - TARGET=imagemagick
  - TARGET=apache
  - TARGET=modperl
  - TARGET=mecab
  - TARGET=rrdtool
before_install: git submodule update --init
install: "make test-deps"
script: "make test"
notifications:
  email:
    - wakaba@suikawiki.org
  irc:
    channels:
      - "irc.suikawiki.org#mechanize"
    use_notice: true
