perl:
  - "5.18"
#  - "5.8"
env:
  matrix:
    - TARGET=normal
    - TARGET=scan
    - TARGET=perl
    - TARGET=imagemagick
    - TARGET=apache
    - TARGET=modperl
    - TARGET=mecab
    - TARGET=rrdtool
    - TARGET=svn
before_install: git submodule update --init
install: "make test-deps"
script: "make test"
notifications:
  email:
    - wakaba@suikawiki.org
  irc:
    channels:
      - "irc.suikawiki.org#mechanize"
    use_notice: true
